dependencies:
  - pip
  - foundry-transforms-lib-python>=0.578.0
  - pip:
    - scikit-learn
    - streamlit-extras
    - squidpy
    - split-file-reader
    - st_pages
    - natsort
    - dill
    - pympler
    - objsize
    - PhenoGraph
    - parmap
    - setuptools-scm
    - scanpy
    
